# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import algorithmia_api_client
from algorithmia_api_client.models.paged_builds_list import PagedBuildsList  # noqa: E501
from algorithmia_api_client.rest import ApiException


class TestPagedBuildsList(unittest.TestCase):
    """PagedBuildsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedBuildsList(self):
        """Test PagedBuildsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = algorithmia_api_client.models.paged_builds_list.PagedBuildsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
