# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import algorithmia_api_client
from algorithmia_api_client.models.update_request import UpdateRequest  # noqa: E501
from algorithmia_api_client.rest import ApiException


class TestUpdateRequest(unittest.TestCase):
    """UpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateRequest(self):
        """Test UpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = algorithmia_api_client.models.update_request.UpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
