# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import algorithmia_api_client
from algorithmia_api_client.models.scm_connection_with_oauth_username import ScmConnectionWithOauthUsername  # noqa: E501
from algorithmia_api_client.rest import ApiException


class TestScmConnectionWithOauthUsername(unittest.TestCase):
    """ScmConnectionWithOauthUsername unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScmConnectionWithOauthUsername(self):
        """Test ScmConnectionWithOauthUsername"""
        # FIXME: construct object with mandatory attributes with example values
        # model = algorithmia_api_client.models.scm_connection_with_oauth_username.ScmConnectionWithOauthUsername()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
