# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import algorithmia_api_client
from algorithmia_api_client.api.default_api import DefaultApi  # noqa: E501
from algorithmia_api_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = algorithmia_api_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_organization_member(self):
        """Test case for add_organization_member

        Add a user as a member of a given organization  # noqa: E501
        """
        pass

    def test_algorithms_username_algoname_compile_post(self):
        """Test case for algorithms_username_algoname_compile_post

        Compile algorithm  # noqa: E501
        """
        pass

    def test_commit_log_for_repository(self):
        """Test case for commit_log_for_repository

        Gets the list of commits for a repository  # noqa: E501
        """
        pass

    def test_create_algorithm(self):
        """Test case for create_algorithm

        Create Algorithm  # noqa: E501
        """
        pass

    def test_create_organization(self):
        """Test case for create_organization

        Creates an Organization owned by the caller  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Creates an Algorithmia user in the system  # noqa: E501
        """
        pass

    def test_delete_algorithm(self):
        """Test case for delete_algorithm

        Delete Algorithm  # noqa: E501
        """
        pass

    def test_delete_config_entry(self):
        """Test case for delete_config_entry

        Delete a config entry represented by the provided keyname  # noqa: E501
        """
        pass

    def test_delete_favicon(self):
        """Test case for delete_favicon

        Delete favicon for the Algorithmia instance  # noqa: E501
        """
        pass

    def test_delete_logo(self):
        """Test case for delete_logo

        Delete logo for the Algorithmia instance  # noqa: E501
        """
        pass

    def test_delete_organization(self):
        """Test case for delete_organization

        Delete an organization  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a user represented by the provided username  # noqa: E501
        """
        pass

    def test_get_algorithm(self):
        """Test case for get_algorithm

        Get Algorithm  # noqa: E501
        """
        pass

    def test_get_algorithm_build_by_id(self):
        """Test case for get_algorithm_build_by_id

        Get individual algorithm build by ID  # noqa: E501
        """
        pass

    def test_get_algorithm_build_logs(self):
        """Test case for get_algorithm_build_logs

        Get Algorithm build logs  # noqa: E501
        """
        pass

    def test_get_algorithm_builds(self):
        """Test case for get_algorithm_builds

        Get Algorithm builds  # noqa: E501
        """
        pass

    def test_get_algorithm_hash_version(self):
        """Test case for get_algorithm_hash_version

        Get Algorithm by Hash Version  # noqa: E501
        """
        pass

    def test_get_algorithm_versions(self):
        """Test case for get_algorithm_versions

        Get Algorithm versions  # noqa: E501
        """
        pass

    def test_get_config_entry(self):
        """Test case for get_config_entry

        Get a frontend config entry represeted by the provided keyname  # noqa: E501
        """
        pass

    def test_get_favicon(self):
        """Test case for get_favicon

        Get favicon for the Algorithmia instance  # noqa: E501
        """
        pass

    def test_get_frontend_config_entries(self):
        """Test case for get_frontend_config_entries

        Lists all frontend configuration values  # noqa: E501
        """
        pass

    def test_get_logo(self):
        """Test case for get_logo

        Get logo for the Algorithmia instance  # noqa: E501
        """
        pass

    def test_get_organization(self):
        """Test case for get_organization

        Get an organization represented by the provided orgName  # noqa: E501
        """
        pass

    def test_get_organizations(self):
        """Test case for get_organizations

        Lists all organizations  # noqa: E501
        """
        pass

    def test_get_package_set_builds(self):
        """Test case for get_package_set_builds

        Name of a package set  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get a user represented by the provided username  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Lists all managed users  # noqa: E501
        """
        pass

    def test_list_entities_for_label(self):
        """Test case for list_entities_for_label

        List the unique set of entities associated with the token associated to the connection established between the user and the SCM configuration (determined by label)  # noqa: E501
        """
        pass

    def test_list_members(self):
        """Test case for list_members

        List of members with their roles in a given organization  # noqa: E501
        """
        pass

    def test_list_scm_connections(self):
        """Test case for list_scm_connections

        List the SCM connections associated with this user  # noqa: E501
        """
        pass

    def test_list_scm_integrations(self):
        """Test case for list_scm_integrations

        Get the list of SCM systems that have been configured with this cluster  # noqa: E501
        """
        pass

    def test_publish_algorithm(self):
        """Test case for publish_algorithm

        Publish Algorithm  # noqa: E501
        """
        pass

    def test_remove_organization_member(self):
        """Test case for remove_organization_member

        Remove a user from an organization  # noqa: E501
        """
        pass

    def test_update_algorithm(self):
        """Test case for update_algorithm

        Update Algorithm  # noqa: E501
        """
        pass

    def test_update_build_status(self):
        """Test case for update_build_status

        Update the status of a package set build  # noqa: E501
        """
        pass

    def test_update_config_entry(self):
        """Test case for update_config_entry

        Update or insert a config entry represented by the provided keyname  # noqa: E501
        """
        pass

    def test_update_favicon(self):
        """Test case for update_favicon

        Update favicon for the Algorithmia instance  # noqa: E501
        """
        pass

    def test_update_logo(self):
        """Test case for update_logo

        Update logo for the Algorithmia instance  # noqa: E501
        """
        pass

    def test_update_package_set(self):
        """Test case for update_package_set

        Update a package set  # noqa: E501
        """
        pass

    def test_update_scm_connection_owner(self):
        """Test case for update_scm_connection_owner

        Update the owner of the SCM connection  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a user represented by the provided username  # noqa: E501
        """
        pass

    def test_upload_profile_image(self):
        """Test case for upload_profile_image

        Upload a profile picture  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
