# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Details(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'summary': 'str',
        'label': 'str',
        'tagline': 'str'
    }

    attribute_map = {
        'summary': 'summary',
        'label': 'label',
        'tagline': 'tagline'
    }

    def __init__(self, summary=None, label=None, tagline=None):  # noqa: E501
        """Details - a model defined in OpenAPI"""  # noqa: E501

        self._summary = None
        self._label = None
        self._tagline = None
        self.discriminator = None

        if summary is not None:
            self.summary = summary
        if label is not None:
            self.label = label
        if tagline is not None:
            self.tagline = tagline

    @property
    def summary(self):
        """Gets the summary of this Details.  # noqa: E501


        :return: The summary of this Details.  # noqa: E501
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this Details.


        :param summary: The summary of this Details.  # noqa: E501
        :type: str
        """

        self._summary = summary

    @property
    def label(self):
        """Gets the label of this Details.  # noqa: E501


        :return: The label of this Details.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Details.


        :param label: The label of this Details.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def tagline(self):
        """Gets the tagline of this Details.  # noqa: E501


        :return: The tagline of this Details.  # noqa: E501
        :rtype: str
        """
        return self._tagline

    @tagline.setter
    def tagline(self, tagline):
        """Sets the tagline of this Details.


        :param tagline: The tagline of this Details.  # noqa: E501
        :type: str
        """

        self._tagline = tagline

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Details):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
