# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class HashResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'details': 'Details',
        'settings': 'Settings',
        'self_link': 'str'
    }

    attribute_map = {
        'name': 'name',
        'details': 'details',
        'settings': 'settings',
        'self_link': 'self_link'
    }

    def __init__(self, name=None, details=None, settings=None, self_link=None):  # noqa: E501
        """HashResponse - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._details = None
        self._settings = None
        self._self_link = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if details is not None:
            self.details = details
        if settings is not None:
            self.settings = settings
        if self_link is not None:
            self.self_link = self_link

    @property
    def name(self):
        """Gets the name of this HashResponse.  # noqa: E501


        :return: The name of this HashResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HashResponse.


        :param name: The name of this HashResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def details(self):
        """Gets the details of this HashResponse.  # noqa: E501


        :return: The details of this HashResponse.  # noqa: E501
        :rtype: Details
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this HashResponse.


        :param details: The details of this HashResponse.  # noqa: E501
        :type: Details
        """

        self._details = details

    @property
    def settings(self):
        """Gets the settings of this HashResponse.  # noqa: E501


        :return: The settings of this HashResponse.  # noqa: E501
        :rtype: Settings
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this HashResponse.


        :param settings: The settings of this HashResponse.  # noqa: E501
        :type: Settings
        """

        self._settings = settings

    @property
    def self_link(self):
        """Gets the self_link of this HashResponse.  # noqa: E501


        :return: The self_link of this HashResponse.  # noqa: E501
        :rtype: str
        """
        return self._self_link

    @self_link.setter
    def self_link(self, self_link):
        """Sets the self_link of this HashResponse.


        :param self_link: The self_link of this HashResponse.  # noqa: E501
        :type: str
        """

        self._self_link = self_link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HashResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
