# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class VersionRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'details': 'Details',
        'settings': 'SettingsPublish',
        'version_info': 'VersionInfoPublish'
    }

    attribute_map = {
        'details': 'details',
        'settings': 'settings',
        'version_info': 'version_info'
    }

    def __init__(self, details=None, settings=None, version_info=None):  # noqa: E501
        """VersionRequest - a model defined in OpenAPI"""  # noqa: E501

        self._details = None
        self._settings = None
        self._version_info = None
        self.discriminator = None

        if details is not None:
            self.details = details
        if settings is not None:
            self.settings = settings
        if version_info is not None:
            self.version_info = version_info

    @property
    def details(self):
        """Gets the details of this VersionRequest.  # noqa: E501


        :return: The details of this VersionRequest.  # noqa: E501
        :rtype: Details
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this VersionRequest.


        :param details: The details of this VersionRequest.  # noqa: E501
        :type: Details
        """

        self._details = details

    @property
    def settings(self):
        """Gets the settings of this VersionRequest.  # noqa: E501


        :return: The settings of this VersionRequest.  # noqa: E501
        :rtype: SettingsPublish
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this VersionRequest.


        :param settings: The settings of this VersionRequest.  # noqa: E501
        :type: SettingsPublish
        """

        self._settings = settings

    @property
    def version_info(self):
        """Gets the version_info of this VersionRequest.  # noqa: E501


        :return: The version_info of this VersionRequest.  # noqa: E501
        :rtype: VersionInfoPublish
        """
        return self._version_info

    @version_info.setter
    def version_info(self, version_info):
        """Sets the version_info of this VersionRequest.


        :param version_info: The version_info of this VersionRequest.  # noqa: E501
        :type: VersionInfoPublish
        """

        self._version_info = version_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VersionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
